<?php

/**
 * @var Magento\Framework\View\Element\Template $block
 */

?>

<div>
    <h5>CUSTOMER CARE</h5>
    <ul>
        <li>
            <a href="contact/">Contact</a>
        </li>
        <li>
            <a href="#">My Account</a>
        </li>
        <li>
            <a href="#">FAQs</a>
        </li>
        <li>
            <a href="#">Terms & Conditions</a>
        </li>
        <li>
            <a href="privacy-policy-cookie-restriction-mode/">Privacy & Cookies</a>
        </li>
    </ul>
</div>
<div>
    <h5>SHIPPING INFO</h5>
    <ul>
        <li>
            <a href="#">Delivery Options</a>
        </li>
        <li>
            <a href="sales/guest/form/">Returns Policy</a>
        </li>
        <li>
            <a href="#">Make a Return</a>
        </li>
    </ul>
</div>
<div>
    <h5>SOCIAL</h5>
    <ul>
        <li>
            <a href="#">Instagram</a>
        </li>
        <li>
            <a href="#">Facebook</a>
        </li>
        <li>
            <a href="#">Blog - The Leisure Manual</a>
        </li>
    </ul>
</div>